export enum Screens {
  BOTTOM = 'BOTTOM',
  TAB = 'TAB',

  //MAIN
  HOME = 'HOME',
  SEARCH = 'SEARCH',
  VIDEO = 'VIDEO',
  NOTIFICATION = 'NOTIFICATION',
  PROFILE = 'PROFILE',
  EDITPROFILE = 'EDITPROFILE',
  TRIPDETAILS = 'TRIPDETAILS',

  //AUTH
  AUTH = 'AUTH',
  REGISTRATION = 'REGISTRATION',

}
